### ISSUE TITLE
getters and setters

### ISSUE THREAD

**Issue by All4Gis** [paretech/klvdata#19]
Make pythonic getters and setters

**Comment by bertram1isu** [comment]
Hi there...  curious why you reverted these changes by All4Gis?  I had pulled a version sometime in November and was successfully using it on one of my MISB streams.  I tried rebuilding my build environment and things no longer work for me.  Traced it down to (I believe) two missing commits from All4Gis that apparently were making things work for me (2d85d2c and 47505ba2).  I have a working copy of them, so I can just maintain my own local fork, but I'd love to be able to stay aligned with the overall development.

Any chance these changes can be reinstated, or did they cause problems elsewhere?

Thanks,
- J.

**Comment by paretech** [comment]
@bertram1isu, thank you for using KLVDATA and for getting in touch. In order to make KLVDATA easier to maintain and to give clear direction to its development, new contributing guidelines were established (see [CONTRIBUTING.md](https://github.com/paretech/klvdata/blob/master/CONTRIBUTING.md)) and applied retroactively to the repository starting from the time the last formal release was made (v0.0.3, e6ef87c). 

I’m sorry that you were impacted by the new guidelines and how they were applied. It is my hope that the guidelines will prevent these types of stability problems in the future and to give the project a clearer development direction. All that being said still doesn’t help you with your problem so let’s see what we can do about that. 

Would you be able to open an [issue](https://github.com/paretech/klvdata/issues/new) that describes the essence of the issue and how a developer can reproduce the issue? If you know why the commits you listed resolve your issue that could be helpful too. Once an issue is open and reproduced we can figure out where to go next to get it resolved. Again sorry for the trouble but hang in there, we’ll figure this out.
