### ISSUE TITLE
Add Parsers 

### ISSUE THREAD

**Issue by Mikaayenson** [paretech/klvdata#2]
I noticed you have other parsers like SensorTrueAltitude not currently active. Is there an issue with these parsers? Do you plan on adding these MappedElementParsers?

**Comment by paretech** [comment]
@Mikaayenson no problem that I know of except that I haven't finished implementing them. I don't think it would be difficult or terribly time consuming at this point as most of the ground work is in place. I personally am not satisfied with my current implementation of the library and have been wanting to perform a re-write. The re-write effort would be several months in the future due to other constraints on time. However, there has been a perceivable amount of interest in this project as of late and you are one of several people asking this question about the other fields. If the library is working for folks as is, I can commit to implementing the remaining MISB ST0106 and nested ST0102 Local Set (LS) fields. I am very curious as to how others are using this library and would very much appreciate some feedback (positive or negative).

**Comment by paretech** [comment]
This is a bug, remaining parsers of MISB ST0601 and nested ST0102 Local Set (LS) fields are missing.

**Comment by Mikaayenson** [comment]
Thanks @paretech. I'm using it exactly how your readme suggested with ffmpeg. I would prefer if there was a better way of obtaining the klv data instead of having to use ffmpeg. 

I would prefer as an example to just pass a video/stream directly to klvdata_test.py

**Comment by paretech** [comment]
@Mikaayenson, thank you for the feedback! That would certainly be a new feature, klvdata likely will not parse streams like MPEG-TS (ISO/IEC 13818-1) directly. klvdata is focused on simply parsing the KLV data as specified by MIST ST0601, ST0102 and possibly other MISB standards. 

However, there are probably ways to make the klvdata demo/test scripts more interesting and useful (like being a more general purpose command line utility, or calling FFMPEG under the hood).

BTW, the addition of the most popular MISB ST0601 and ST0102 local set element parsers are WIP by @All4Gis and can be found in PR #3.

**Comment by Mikaayenson** [comment]
Do you plan on merging this back into Master?

**Comment by paretech** [comment]
Hello @Mikaayenson, 

I do intend on merging @All4Gis changes back in pending a code review and some additional cleanup. Life and day job are a little intense right now so it will likely be a couple of weeks before I can invest the time to complete the task to the level I intend.

In the mean time, you can help with the process if you would like by reviewing the functionality of the changes included in PR #3. I believe there are tests for all the items are in the PR or already in master.

Thank you for your interest and assistance,

-Matt

**Comment by Mikaayenson** [comment]
@paretech will do. I pulled down @All4Gis code a few days ago and ran his new parsers with no issues. I'll keep you posted if i discover something while testing.

**Comment by paretech** [comment]
Mike,

You and @All4Gis are now collaborators on the repo. Too much going on right
now for me to maintain and contribute to the extent and rate I would like.
I'm available to field questions, open to getting on a call as well.

-Matt
